version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/services/fleet-manager"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/services/telemetry-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/services/mission-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/edge-agent"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/services/fleet-manager"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/services/telemetry-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/services/mission-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/edge-agent"
    schedule:
      interval: "weekly"